package docgen

import (
	"bytes"
	"fmt"
	"sort"

	"github.com/olesho/veracity/internal/docgen/ir"
)

// RenderMarkdown produces a deterministic MODULES.md for a project's IR,
// including agent-written summaries/descriptions from the store when they are
// fresh (a placeholder otherwise).
func RenderMarkdown(doc ir.IR, store *Summaries) []byte {
	if store == nil {
		store = newSummaries()
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s — Modules\n\n", doc.Subproject)
	b.WriteString("_Auto-generated by `veracity docs`. Structure is from the AST; summaries are agent-written and cached by content hash._\n")

	mods := append([]ir.Module(nil), doc.Modules...)
	sort.SliceStable(mods, func(i, j int) bool { return mods[i].Path < mods[j].Path })

	if len(mods) == 0 {
		b.WriteString("\n_No modules found._\n")
		return b.Bytes()
	}

	for _, m := range mods {
		fmt.Fprintf(&b, "\n## Module: %s (`%s`)\n\n", m.Name, m.Path)
		if s := store.moduleSummary(m); s != "" {
			b.WriteString(s)
			b.WriteString("\n")
		} else {
			b.WriteString("_(summary pending — run the veracity-docs skill)_\n")
		}
		if m.DocComment != "" {
			fmt.Fprintf(&b, "\n> %s\n", m.DocComment)
		}

		if len(m.Exports) > 0 {
			b.WriteString("\n### Exported Types & Functions\n")
			for _, e := range m.Exports {
				fmt.Fprintf(&b, "\n#### `%s`\n", e.Signature)
				if e.DocComment != "" {
					b.WriteString(e.DocComment)
					b.WriteString("\n")
				}
			}
		}

		if len(m.Interfaces) > 0 {
			b.WriteString("\n### Interfaces (Boundaries)\n")
			for _, iface := range m.Interfaces {
				fmt.Fprintf(&b, "\n#### `%s`\n", iface.Name)
				if d := store.interfaceDescription(m, iface); d != "" {
					b.WriteString(d)
					b.WriteString("\n")
				}
				if iface.DocComment != "" {
					fmt.Fprintf(&b, "\n> %s\n", iface.DocComment)
				}
				if len(iface.Methods) > 0 {
					b.WriteString("\n")
					for _, meth := range iface.Methods {
						fmt.Fprintf(&b, "- `%s`\n", meth.Signature)
					}
				}
			}
		}
	}
	return b.Bytes()
}
